version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - Harpia
          filters:
            branches:
              only:
                - master

jobs:
  build:
    docker:
      - image: cimg/python:3.10.6
    working_directory: ~/workspace
    environment:
      SERVICE_NAME: harp-ui
      SERVICE_VERSION: v1.1.20
      SERVICE_NAMESPACE: dev
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check variable
          command: echo ${PROJECT_ID}
      - run:
          name: Build docker image
          command: docker build -t ${SERVICE_NAME}:latest .
      - run:
          name: Set the tag for the image
          command: docker tag ${SERVICE_NAME} theharpia/${SERVICE_NAME}:${SERVICE_VERSION}
      - run:
          name: Login to dockerhub
          command: docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASS}
      - run:
          name: Push image to DockerHub
          command: docker push theharpia/${SERVICE_NAME}:${SERVICE_VERSION}
